stages:
  train:
    cmd: python src/cli.py --train
    deps:
      - src/cli.py
      - src/dataloader.py
      - src/encoder.py
      - src/decoder.py
      - src/generator.py
      - src/discriminator_block.py
      - src/discriminator.py
      - src/adversarial_loss.py
      - src/pixelwise_loss.py
      - src/helper.py
      - src/utils.py
      - src/trainer.py
      - ./config.yml
      - ./data
    # outs:
    #   - ./checkpoints/:
    #       persist: True
    #   - ./research/:
    #       persist: True
    #   - ./outputs/:
    #       persist: True

  test:
    cmd: python src/cli.py --test
    deps:
      - src/cli.py
      - src/tester.py
      - src/utils.py
      - src/helper.py
      - ./config.yml
      - ./checkpoints/

    outs:
      - ./outputs/:
          persist: True
